package io.github.rezeros.core.serialize.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_generic_class.proto

public final class MyGenericClass {
  private MyGenericClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DynamicObjectHolderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DynamicObjectHolder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     * @return Whether the serializedObject field is set.
     */
    boolean hasSerializedObject();
    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     * @return The serializedObject.
     */
    com.google.protobuf.Any getSerializedObject();
    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getSerializedObjectOrBuilder();
  }
  /**
   * Protobuf type {@code DynamicObjectHolder}
   */
  public static final class DynamicObjectHolder extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DynamicObjectHolder)
      DynamicObjectHolderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DynamicObjectHolder.newBuilder() to construct.
    private DynamicObjectHolder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicObjectHolder() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DynamicObjectHolder();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyGenericClass.internal_static_DynamicObjectHolder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyGenericClass.internal_static_DynamicObjectHolder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyGenericClass.DynamicObjectHolder.class, MyGenericClass.DynamicObjectHolder.Builder.class);
    }

    public static final int SERIALIZED_OBJECT_FIELD_NUMBER = 1;
    private com.google.protobuf.Any serializedObject_;
    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     * @return Whether the serializedObject field is set.
     */
    @java.lang.Override
    public boolean hasSerializedObject() {
      return serializedObject_ != null;
    }
    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     * @return The serializedObject.
     */
    @java.lang.Override
    public com.google.protobuf.Any getSerializedObject() {
      return serializedObject_ == null ? com.google.protobuf.Any.getDefaultInstance() : serializedObject_;
    }
    /**
     * <pre>
     * Define a field to hold the serialized object
     * </pre>
     *
     * <code>.google.protobuf.Any serialized_object = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getSerializedObjectOrBuilder() {
      return getSerializedObject();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serializedObject_ != null) {
        output.writeMessage(1, getSerializedObject());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serializedObject_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSerializedObject());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyGenericClass.DynamicObjectHolder)) {
        return super.equals(obj);
      }
      MyGenericClass.DynamicObjectHolder other = (MyGenericClass.DynamicObjectHolder) obj;

      if (hasSerializedObject() != other.hasSerializedObject()) return false;
      if (hasSerializedObject()) {
        if (!getSerializedObject()
            .equals(other.getSerializedObject())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSerializedObject()) {
        hash = (37 * hash) + SERIALIZED_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getSerializedObject().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyGenericClass.DynamicObjectHolder parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyGenericClass.DynamicObjectHolder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyGenericClass.DynamicObjectHolder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyGenericClass.DynamicObjectHolder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyGenericClass.DynamicObjectHolder prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DynamicObjectHolder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DynamicObjectHolder)
        MyGenericClass.DynamicObjectHolderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyGenericClass.internal_static_DynamicObjectHolder_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyGenericClass.internal_static_DynamicObjectHolder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyGenericClass.DynamicObjectHolder.class, MyGenericClass.DynamicObjectHolder.Builder.class);
      }

      // Construct using MyGenericClass.DynamicObjectHolder.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (serializedObjectBuilder_ == null) {
          serializedObject_ = null;
        } else {
          serializedObject_ = null;
          serializedObjectBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyGenericClass.internal_static_DynamicObjectHolder_descriptor;
      }

      @java.lang.Override
      public MyGenericClass.DynamicObjectHolder getDefaultInstanceForType() {
        return MyGenericClass.DynamicObjectHolder.getDefaultInstance();
      }

      @java.lang.Override
      public MyGenericClass.DynamicObjectHolder build() {
        MyGenericClass.DynamicObjectHolder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MyGenericClass.DynamicObjectHolder buildPartial() {
        MyGenericClass.DynamicObjectHolder result = new MyGenericClass.DynamicObjectHolder(this);
        if (serializedObjectBuilder_ == null) {
          result.serializedObject_ = serializedObject_;
        } else {
          result.serializedObject_ = serializedObjectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyGenericClass.DynamicObjectHolder) {
          return mergeFrom((MyGenericClass.DynamicObjectHolder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyGenericClass.DynamicObjectHolder other) {
        if (other == MyGenericClass.DynamicObjectHolder.getDefaultInstance()) return this;
        if (other.hasSerializedObject()) {
          mergeSerializedObject(other.getSerializedObject());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getSerializedObjectFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.google.protobuf.Any serializedObject_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> serializedObjectBuilder_;
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       * @return Whether the serializedObject field is set.
       */
      public boolean hasSerializedObject() {
        return serializedObjectBuilder_ != null || serializedObject_ != null;
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       * @return The serializedObject.
       */
      public com.google.protobuf.Any getSerializedObject() {
        if (serializedObjectBuilder_ == null) {
          return serializedObject_ == null ? com.google.protobuf.Any.getDefaultInstance() : serializedObject_;
        } else {
          return serializedObjectBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public Builder setSerializedObject(com.google.protobuf.Any value) {
        if (serializedObjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serializedObject_ = value;
          onChanged();
        } else {
          serializedObjectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public Builder setSerializedObject(
          com.google.protobuf.Any.Builder builderForValue) {
        if (serializedObjectBuilder_ == null) {
          serializedObject_ = builderForValue.build();
          onChanged();
        } else {
          serializedObjectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public Builder mergeSerializedObject(com.google.protobuf.Any value) {
        if (serializedObjectBuilder_ == null) {
          if (serializedObject_ != null) {
            serializedObject_ =
              com.google.protobuf.Any.newBuilder(serializedObject_).mergeFrom(value).buildPartial();
          } else {
            serializedObject_ = value;
          }
          onChanged();
        } else {
          serializedObjectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public Builder clearSerializedObject() {
        if (serializedObjectBuilder_ == null) {
          serializedObject_ = null;
          onChanged();
        } else {
          serializedObject_ = null;
          serializedObjectBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public com.google.protobuf.Any.Builder getSerializedObjectBuilder() {
        
        onChanged();
        return getSerializedObjectFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getSerializedObjectOrBuilder() {
        if (serializedObjectBuilder_ != null) {
          return serializedObjectBuilder_.getMessageOrBuilder();
        } else {
          return serializedObject_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : serializedObject_;
        }
      }
      /**
       * <pre>
       * Define a field to hold the serialized object
       * </pre>
       *
       * <code>.google.protobuf.Any serialized_object = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getSerializedObjectFieldBuilder() {
        if (serializedObjectBuilder_ == null) {
          serializedObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getSerializedObject(),
                  getParentForChildren(),
                  isClean());
          serializedObject_ = null;
        }
        return serializedObjectBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DynamicObjectHolder)
    }

    // @@protoc_insertion_point(class_scope:DynamicObjectHolder)
    private static final MyGenericClass.DynamicObjectHolder DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyGenericClass.DynamicObjectHolder();
    }

    public static MyGenericClass.DynamicObjectHolder getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicObjectHolder>
        PARSER = new com.google.protobuf.AbstractParser<DynamicObjectHolder>() {
      @java.lang.Override
      public DynamicObjectHolder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DynamicObjectHolder> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicObjectHolder> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MyGenericClass.DynamicObjectHolder getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DynamicObjectHolder_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DynamicObjectHolder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026my_generic_class.proto\032\031google/protobu" +
      "f/any.proto\"F\n\023DynamicObjectHolder\022/\n\021se" +
      "rialized_object\030\001 \001(\0132\024.google.protobuf." +
      "Anyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_DynamicObjectHolder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DynamicObjectHolder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DynamicObjectHolder_descriptor,
        new java.lang.String[] { "SerializedObject", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
